"""The library: everything he has made, filed by day (ADR-007 M10).

"Quiero orden en el sistema" — readings, writings, speaking answers and
activity sets are already stored with a date; this module is the one place
that groups them into days so each tab can show its own shelf, and the one
place that deletes something generated by mistake.

Deletion is real (the row goes) but scoped: removing a reading never touches
the vocabulary, errors or reviews it produced — those are learning history,
not the artifact.
"""

from __future__ import annotations

import json
import sqlite3
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE))
from app import db  # noqa: E402

TEXT_KINDS = ("reading", "writing", "speaking")


def _day_bucket(days: dict, date: str) -> dict:
    return days.setdefault(date, {"date": date, "reading": [], "writing": [],
                                  "speaking": [], "activities": []})


def by_day(conn: sqlite3.Connection, kind: "str | None" = None,
           limit_days: int = 60) -> "list[dict]":
    """Every artifact grouped by date, newest day first."""
    days: "dict[str, dict]" = {}

    kinds = (kind,) if kind in TEXT_KINDS else TEXT_KINDS
    placeholders = ",".join("?" * len(kinds))
    for row in conn.execute(
            f"SELECT id, kind, title, date, level, topic, finished_at, "
            f"words_produced, errors_count, corrected, tts_path, source, "
            f"LENGTH(body) AS length FROM texts "
            f"WHERE kind IN ({placeholders}) AND body IS NOT NULL "
            f"AND date IS NOT NULL ORDER BY date DESC, id DESC", kinds):
        d = dict(row)
        bucket = _day_bucket(days, d["date"])
        bucket[d["kind"]].append({
            "id": d["id"], "title": d["title"], "level": d["level"],
            "topic": d["topic"], "finished": d["finished_at"] is not None,
            "narrated": d["tts_path"] is not None,
            "words_produced": d["words_produced"],
            "errors_count": d["errors_count"],
            "generated": (d["source"] or "").startswith("generated"),
        })

    if kind in (None, "activities"):
        for row in conn.execute(
                "SELECT id, date, kind, title, score, total, completed_at "
                "FROM activities WHERE kind != 'tip' "
                "ORDER BY date DESC, id"):
            d = dict(row)
            _day_bucket(days, d["date"])["activities"].append({
                "id": d["id"], "kind": d["kind"], "title": d["title"],
                "score": d["score"], "total": d["total"],
                "completed": d["completed_at"] is not None,
            })

    ordered = sorted(days.values(), key=lambda x: x["date"], reverse=True)
    return ordered[:limit_days]


def delete_text(conn: sqlite3.Connection, text_id: int) -> dict:
    """Remove a reading/writing/speaking artifact. Words learned from it and
    errors it revealed stay — deleting a bad reading must not rewrite history."""
    row = conn.execute("SELECT kind, title, audio_path FROM texts WHERE id=?",
                       (text_id,)).fetchone()
    if row is None:
        raise ValueError(f"text {text_id} not found")
    conn.execute("DELETE FROM texts WHERE id=?", (text_id,))
    conn.commit()
    return {"deleted": text_id, "kind": row["kind"], "title": row["title"]}


def delete_activity(conn: sqlite3.Connection, activity_id: int) -> dict:
    row = conn.execute("SELECT kind, title FROM activities WHERE id=?",
                       (activity_id,)).fetchone()
    if row is None:
        raise ValueError(f"activity {activity_id} not found")
    conn.execute("DELETE FROM activities WHERE id=?", (activity_id,))
    conn.commit()
    return {"deleted": activity_id, "kind": row["kind"], "title": row["title"]}


def text_detail(conn: sqlite3.Connection, text_id: int) -> dict:
    """A finished writing/speaking piece with its correction, for the shelf."""
    row = conn.execute("SELECT * FROM texts WHERE id=?", (text_id,)).fetchone()
    if row is None:
        raise ValueError(f"text {text_id} not found")
    d = dict(row)
    if d.get("correction"):
        d["correction"] = json.loads(d["correction"])
    for key in ("questions", "words_target", "tts_marks"):
        if d.get(key):
            d[key] = json.loads(d[key])
    return d
