"""ObsidianAdapter: export the Personal English Model to the vault (ADR-006 D3).

Writes generated markdown with [[wikilinks]] into English_System/English OS/:

    Profile.md            — counts, recent sessions, top error categories
    Errors/<Category>.md  — real corrections grouped by category
    Words/<word>.md       — one note per LEARNING/FAMILIAR word

Everything under "English OS/" is regenerated on every run (idempotent) and
marked as generated — Eddie's own notes belong anywhere else in the vault and
are never touched. Hard data lives in SQLite; this is the readable layer.
"""

from __future__ import annotations

import re
import shutil
import sqlite3
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE))
from app import db, model  # noqa: E402

VAULT = BASE / "English_System"
ROOT_NAME = "English OS"

HEADER = "> [!info] Generated by English OS — edits here will be overwritten.\n\n"


def note_name(word: str) -> str:
    """Vault-safe note name for a word."""
    clean = re.sub(r'[\\/:*?"<>|#^\[\]]', "", word).strip()
    return clean[:80] or "untitled"


def _write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def _status_line(counts: "dict[str, int]") -> str:
    return " · ".join(
        f"**{counts.get(s, 0)}** {s.lower()}" for s in db.STATUSES
    )


def _export_material(conn: sqlite3.Connection, root: Path) -> int:
    """Readings, writings, podcasts and one note per day (ADR-008 D6).

    The vault stops being a summary and becomes the archive: what he read,
    what he wrote and how it was corrected, what he listened to, and a daily
    page tying it together — so a month later he can open a date and see the
    actual work, not just a number.
    """
    import json as _json
    notes = 0
    days: "dict[str, dict]" = {}

    def day(d: str) -> dict:
        return days.setdefault(d, {"readings": [], "writings": [],
                                   "podcasts": [], "activities": []})

    for row in conn.execute(
            "SELECT id, kind, title, date, level, body, words_produced, "
            "errors_count, correction, quiz_score, quiz_total, words_target "
            "FROM texts WHERE body IS NOT NULL AND date IS NOT NULL "
            "ORDER BY date DESC LIMIT 400"):
        r = dict(row)
        name = f"{r['date']} {note_name(r['title'] or 'untitled')}"
        kind = r["kind"]

        if kind == "reading":
            body = HEADER + f"# {r['title']}\n\n"
            if r["level"]:
                body += f"*{r['level']}*"
            if r["quiz_total"]:
                body += f" · comprensión {r['quiz_score']}/{r['quiz_total']}"
            body += "\n\n" + (r["body"] or "") + "\n"
            if r["words_target"]:
                targets = _json.loads(r["words_target"])
                body += "\n## Palabras objetivo\n\n" + " · ".join(
                    f"[[Words/{note_name(w)}|{w}]]" for w in targets) + "\n"
            _write(root / "Readings" / f"{name}.md", body)
            day(r["date"])["readings"].append((name, r["title"], r["quiz_score"],
                                               r["quiz_total"]))
            notes += 1

        elif kind in ("writing", "speaking"):
            body = HEADER + f"# {r['title']}\n\n"
            body += f"*{kind}* · {r['words_produced'] or 0} palabras · "
            body += f"{r['errors_count'] or 0} correcciones\n\n"
            body += "## Lo que produje\n\n" + (r["body"] or "") + "\n"
            if r["correction"]:
                c = _json.loads(r["correction"])
                if c.get("errors"):
                    body += "\n## Correcciones\n\n"
                    for e in c["errors"]:
                        body += (f"- ✗ {e['original']}\n  - ✓ {e['correction']}\n"
                                 f"  - *{e.get('category','')}* — "
                                 f"{e.get('explanation','')}\n")
                if c.get("tenses_used"):
                    body += ("\n**Tiempos verbales usados:** "
                             + ", ".join(c["tenses_used"]) + "\n")
                for key, label in (("improved_version", "Versión B2"),
                                   ("natural_version", "Versión natural"),
                                   ("strength", "Fortaleza"),
                                   ("practice_next", "A practicar")):
                    if c.get(key):
                        body += f"\n**{label}:** {c[key]}\n"
            _write(root / "Writings" / f"{name}.md", body)
            day(r["date"])["writings"].append((name, r["title"],
                                               r["words_produced"],
                                               r["errors_count"], kind))
            notes += 1

        elif kind == "podcast":
            body = HEADER + f"# {r['title']}\n\n"
            if r["quiz_total"]:
                body += f"*comprensión {r['quiz_score']}/{r['quiz_total']}*\n\n"
            body += "## Transcript\n\n" + (r["body"] or "") + "\n"
            _write(root / "Podcasts" / f"{name}.md", body)
            day(r["date"])["podcasts"].append((name, r["title"], r["quiz_score"],
                                               r["quiz_total"]))
            notes += 1

    for row in conn.execute(
            "SELECT date, title, score, total FROM activities "
            "WHERE kind != 'tip' AND score IS NOT NULL ORDER BY date DESC LIMIT 200"):
        day(row["date"])["activities"].append((row["title"], row["score"],
                                               row["total"]))

    sessions = {r["date"]: dict(r) for r in conn.execute("SELECT * FROM sessions")}
    for d in set(days) | set(sessions):
        day(d)
    for d, content in days.items():
        s = sessions.get(d, {})
        body = HEADER + f"# {d}\n\n"
        if s.get("cards_reviewed"):
            rate = s.get("again_rate")
            body += (f"**Anki:** {s['cards_reviewed']} cards"
                     + (f" · {round(rate * 100)}% again" if rate is not None else "")
                     + "\n")
        for label, key in (("Lectura", "reading_minutes"),
                           ("Escucha", "listening_minutes"),
                           ("Speaking", "speaking_minutes")):
            if s.get(key):
                body += f"**{label}:** {round(float(s[key]))} min\n"
        if content["readings"]:
            body += "\n## Leí\n\n" + "".join(
                f"- [[Readings/{n}|{t}]]"
                + (f" — comprensión {sc}/{tt}\n" if tt else "\n")
                for n, t, sc, tt in content["readings"])
        if content["podcasts"]:
            body += "\n## Escuché\n\n" + "".join(
                f"- [[Podcasts/{n}|{t}]]"
                + (f" — comprensión {sc}/{tt}\n" if tt else "\n")
                for n, t, sc, tt in content["podcasts"])
        if content["writings"]:
            body += "\n## Produje\n\n" + "".join(
                f"- [[Writings/{n}|{t}]] — {k}, {w or 0} palabras, "
                f"{e or 0} correcciones\n"
                for n, t, w, e, k in content["writings"])
        if content["activities"]:
            body += "\n## Practiqué\n\n" + "".join(
                f"- {t} — {sc}/{tt}\n" for t, sc, tt in content["activities"])
        body += "\n[[Profile]]\n"
        _write(root / "Days" / f"{d}.md", body)
        notes += 1
    return notes


def export(conn: sqlite3.Connection, vault: "Path | None" = None) -> dict:
    vault = Path(vault or VAULT)
    if not vault.exists():
        print(f"⏭  obsidian: no existe el vault {vault} — skip.")
        return {"notes": 0}
    root = vault / ROOT_NAME
    if root.exists():
        shutil.rmtree(root)

    counts = dict(conn.execute(
        "SELECT status, COUNT(*) FROM words GROUP BY status").fetchall())
    sessions = conn.execute(
        "SELECT * FROM sessions ORDER BY date DESC LIMIT 14").fetchall()
    cats = conn.execute(
        "SELECT category, SUM(recurrences) AS n FROM errors "
        "WHERE category IS NOT NULL GROUP BY category ORDER BY n DESC").fetchall()
    words = conn.execute(
        "SELECT * FROM words WHERE status IN ('LEARNING','FAMILIAR') "
        "ORDER BY status, normalized").fetchall()

    notes = 0

    # ── Words/ ────────────────────────────────────────────────────────────
    by_status: "dict[str, list[str]]" = {"LEARNING": [], "FAMILIAR": []}
    for w in words:
        name = note_name(w["word"])
        by_status[w["status"]].append(name)
        body = HEADER
        body += "---\n"
        body += f"status: {w['status']}\n"
        body += f"kind: {w['kind']}\n"
        if w["cefr"]:
            body += f"cefr: {w['cefr']}\n"
        body += f"reviews: {w['review_count'] or 0}\n"
        body += f"interval_days: {w['interval_days'] or 0}\n"
        body += f"times_used: {w['times_used'] or 0}\n"
        if w["last_reviewed_on"]:
            body += f"last_reviewed: {w['last_reviewed_on'][:10]}\n"
        body += "---\n\n"
        body += f"# {w['word']}\n\n"
        if w["pronunciation"]:
            body += f"*/{w['pronunciation']}/*\n\n"
        if w["meaning_en"]:
            body += f"{w['meaning_en']}\n\n"
        if w["example_en"]:
            body += f"> {w['example_en']}\n\n"
        if w["meaning_es"]:
            body += f"**ES:** {w['meaning_es']}\n\n"
        body += f"Part of [[Profile|my English profile]].\n"
        _write(root / "Words" / f"{name}.md", body)
        notes += 1

    # ── Errors/ ───────────────────────────────────────────────────────────
    for cat_row in cats:
        cat = cat_row["category"]
        rows = conn.execute(
            "SELECT * FROM errors WHERE category=? ORDER BY date DESC",
            (cat,)).fetchall()
        body = HEADER + f"# {cat}\n\n"
        body += f"{cat_row['n']} occurrence(s) recorded. See [[Profile]].\n\n"
        for e in rows:
            body += f"## {e['error'] or e['original'] or 'error'}\n\n"
            if e["original"]:
                body += f"- ✗ {e['original']}\n"
            if e["correction"]:
                body += f"- ✓ {e['correction']}\n"
            if e["explanation"]:
                body += f"- {e['explanation']}\n"
            meta = []
            if e["date"]:
                meta.append(e["date"][:10])
            if (e["recurrences"] or 1) > 1:
                meta.append(f"seen ×{e['recurrences']}")
            if meta:
                body += f"- *{', '.join(meta)}*\n"
            body += "\n"
        _write(root / "Errors" / f"{note_name(cat)}.md", body)
        notes += 1

    # ── Days/, Readings/, Writings/, Podcasts/ (M12) ──────────────────────
    notes += _export_material(conn, root)

    # ── Profile.md ────────────────────────────────────────────────────────
    snap = model.snapshot(conn)
    rec = snap["recommendation"]
    perf = snap["review"]
    err = snap["errors"]
    body = HEADER + "# My English profile\n\n"
    body += f"{_status_line(counts)} — {sum(counts.values())} words total.\n\n"
    body += f"**Nivel de trabajo:** {rec['level']} — {rec['reason']}.\n"
    if snap["streak_days"]:
        body += f"**Racha:** {snap['streak_days']} día(s).\n"
    body += "\n## En qué se basa la evaluación\n\n"
    body += "| Fuente | Medida | Muestra | Señal |\n|---|---|---:|---|\n"
    for key in ("recall", "comprehension", "controlled", "production"):
        e = snap["evidence"][key]
        signal = {"stretch": "avanzar", "hold": "en nivel",
                  "consolidate": "consolidar"}.get(e["signal"] or "",
                                                   "sin datos suficientes")
        body += (f"| {e['label']} | {e['display'] or '—'} | "
                 f"{e['n']} {e['unit']} | {signal} |\n")
    body += ("\n*Ningún día sin escribir te deja sin evaluación: recall, "
             "comprensión y práctica también cuentan.*\n\n")
    _ = perf, err

    if cats:
        body += "## Recurring errors\n\n"
        for c in cats:
            body += f"- [[Errors/{note_name(c['category'])}|{c['category']}]] ×{c['n']}\n"
        body += "\n"

    if by_status["LEARNING"]:
        body += "## Learning now\n\n"
        body += " · ".join(f"[[Words/{n}|{n}]]" for n in by_status["LEARNING"]) + "\n\n"
    if by_status["FAMILIAR"]:
        body += "## Getting familiar\n\n"
        body += " · ".join(f"[[Words/{n}|{n}]]" for n in by_status["FAMILIAR"]) + "\n\n"

    if sessions:
        body += "## Días recientes\n\n"
        for s in sessions:
            rate = (f" · {round((s['again_rate'] or 0) * 100)}% again"
                    if s["again_rate"] is not None else "")
            body += (f"- [[Days/{s['date']}]] — {s['cards_reviewed'] or 0} cards"
                     f"{rate}\n")
        body += "\n"
    _write(root / "Profile.md", body)
    notes += 1

    return {"notes": notes}


def run(conn: sqlite3.Connection) -> dict:
    return export(conn)


if __name__ == "__main__":
    print("obsidian →", export(db.connect()))
